services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      #Diz quais são as credenciais
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}   #Vai procurar no .env
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql #Diretorio onde o banco de dados está armazenado
      - ./db/init:/docker-entrypoint-initdb.d:ro   #Diretorio onde os scripts the inicialização estão guardados.
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      #Teste de integridade.
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
